version: "3.8"

services:
  monolith:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hotelio-monolith
    ports:
      - "8084:8080"
    networks:
      - hotelio-net
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://monolith-db:5432/hotelio
      SPRING_DATASOURCE_USERNAME: hotelio
      SPRING_DATASOURCE_PASSWORD: hotelio
      BOOKING_SERVICE_EXTERNAL_HOST: booking-service
      BOOKING_SERVICE_EXTERNAL_PORT: 9090

  monolith-db:
    image: postgres:15
    container_name: hotelio-db
    environment:
      POSTGRES_USER: hotelio
      POSTGRES_PASSWORD: hotelio
      POSTGRES_DB: hotelio
    ports:
      - "5432:5432"
    volumes:
      - monolith-db-data:/var/lib/postgresql/data
    networks:
      - hotelio-net

  kafka:
    image: confluentinc/cp-kafka:7.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    networks:
      - hotelio-net
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - hotelio-net

  booking-service:
    build:
      context: ../hotelio/booking_service
      dockerfile: Dockerfile
    container_name: booking-service
    environment:
      PORT: 9090
      HTTP_PORT: 9091
      MONOLITH_HOST: monolith
      MONOLITH_PORT: 8080
      BOOKING_DB_HOST: booking-db
      BOOKING_DB_PORT: 5432
      BOOKING_DB_USER: booking
      BOOKING_DB_PASSWORD: booking
      BOOKING_DB_NAME: booking
      KAFKA_BROKERS: kafka:9092
      BOOKING_CREATED_TOPIC: booking.created
    networks:
      - hotelio-net
    ports:
      - "9090:9090"
      - "9091:9091"
    depends_on:
      - booking-db

  booking-db:
    image: postgres:15
    container_name: booking-db
    environment:
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
      POSTGRES_DB: booking
    ports:
      - "5433:5432"
    volumes:
      - booking-db-data:/var/lib/postgresql/data
    networks:
      - hotelio-net

  booking-history-service:
    build:
      context: ../hotelio/booking_history_service
      dockerfile: Dockerfile
    container_name: booking-history-service
    environment:
      KAFKA_BROKERS: kafka:9092
      BOOKING_CREATED_TOPIC: booking.created
      POSTGRES_HOST: booking-history-db
      POSTGRES_PORT: 5432
      POSTGRES_USER: booking_history
      POSTGRES_PASSWORD: booking_history
      POSTGRES_DB: booking_history
      PORT: 9094
    networks:
      - hotelio-net
    ports:
      - "9094:9094"
    depends_on:
      - booking-history-db
      - kafka

  booking-history-db:
    image: postgres:15
    container_name: booking-history-db
    environment:
      POSTGRES_USER: booking_history
      POSTGRES_PASSWORD: booking_history
      POSTGRES_DB: booking_history
    ports:
      - "5434:5432"
    volumes:
      - booking-history-db-data:/var/lib/postgresql/data
    networks:
      - hotelio-net

volumes:
  monolith-db-data:
  booking-db-data:
  booking-history-db-data:

networks:
  hotelio-net:
    external: true
