apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking
      version: v1
  template:
    metadata:
      labels:
        app: booking
        version: v1
    spec:
      containers:
        - name: booking
          image: booking-service:v1
          ports:
            - containerPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: booking-v2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: booking
      version: v2
  template:
    metadata:
      labels:
        app: booking
        version: v2
    spec:
      containers:
        - name: booking
          image: booking-service:v2
          ports:
            - containerPort: 8080



---



apiVersion: v1
kind: Service
metadata:
  name: booking
spec:
  selector:
    app: booking
  ports:
    - port: 9090
      targetPort: 8080
      name: http



---



apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: booking-gw
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - booking.local



---



apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: booking-dr
spec:
  host: booking
  subsets:
    - name: v1
      labels:
        version: v1
    - name: v2
      labels:
        version: v2

apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: booking-vs
spec:
  hosts:
    - booking.local
  gateways:
    - booking-gw
  http:
  - match:
    - headers:
        x-feature-enabled:
          exact: "true"
    route:
    - destination:
        host: booking.default.svc.cluster.local
        subset: v2
  - route:
    - destination:
        host: booking.default.svc.cluster.local
        subset: v1
      weight: 90
    - destination:
        host: booking.default.svc.cluster.local
        subset: v2
      weight: 10
