version: '3.8'

services:
  apollo-gateway:
    build: ./gateway
    ports:
      - "4000:4000"
    depends_on:
      - booking-subgraph
      - hotel-subgraph
    environment:
      BOOKING_URL: http://booking-subgraph:4001/
      HOTEL_URL: http://hotel-subgraph:4002/

  booking-subgraph:
    build: ./booking-subgraph
    ports:
      - "4001:4001"

  hotel-subgraph:
    build: ./hotel-subgraph
    ports:
      - "4002:4002"
