apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.appName }}-v1
  labels:
    app: {{ .Values.appName }}
    version: v1
spec:
  replicas: {{ .Values.replicaCount.v1 }}
  selector:
    matchLabels:
      app: {{ .Values.appName }}
      version: v1
  template:
    metadata:
      labels:
        app: {{ .Values.appName }}
        version: v1
    spec:
      containers:
        - name: {{ .Values.appName }}-v1
          image: {{ .Values.images.v1 }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}